#include <iostream>
#include <vector>
#include <deque>
#include <stack>
#include <string>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <array>
#include <list>
#include <forward_list>
#include <queue>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <climits>
#include <fstream>
#include <algorithm>
#include <typeinfo> // typeid().name()
#include <exception>
#include <new>
#include <functional>
#include <memory>
#include <thread>
#include <fstream>
#include <mutex>
#include <condition_variable>
#include <atomic>